  on:
    push:
      branches:
        - new2
    pull_request:
      branches:
        - new2



  jobs:
    build-java:
      runs-on: ubuntu-latest



      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Grant permission
          run: chmod +x gradlew
        - name: build with Gradle
          run: ./gradlew build

        - name: build and push Docker Image
          uses: mr-smithers-excellent/docker-build-push@v4
          with:
            image: saniyaathani/myplatform
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

